{{- if .Values.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysql-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: mysql-primary
                port:
                  number: 3306
  tls:
    - hosts:
      - {{ .Values.ingress.host}}
      secretName: {{ .Values.ingress.secretName}}
{{- end }}